M48
; DRILL file {KiCad 7.0.9-7.0.9~ubuntu22.04.1} date Wed 20 Dec 2023 21:39:56 GMT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-20T21:39:56+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9-7.0.9~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X100.0Y-68.0
X100.0Y-98.0
X180.0Y-68.0
X180.0Y-98.0
T0
M30
